### ISSUE TITLE
[M]사이트 수정사항 

### ISSUE THREAD

**Issue by active-weirdo** [PythonDAS/cochil#4]
http://cochil.devarchi33.com/inputData
![2016-05-24 9 13 30](https://cloud.githubusercontent.com/assets/17562888/15503386/8861cca0-21f4-11e6-817c-0daa3cd4e7ae.png)

박스 안에 그레이폰트 (설명)
"성분 이름을 말하세요" -> ex. 폴리에스테르

**Comment by devarchi33** [comment]
ce4e4eba346f9ff853dfe935bdb34de9aa848dc6
<img width="599" alt="2016-05-25 01 01 06" src="https://cloud.githubusercontent.com/assets/7742818/15510870/2d322bac-2214-11e6-9db0-746a39b277ef.png">

이렇게 수정 했습니다.

**Comment by devarchi33** [comment]
해결 : https://github.com/PythonDAS/cochil/commit/ce4e4eba346f9ff853dfe935bdb34de9aa848dc6
